version: '3.8'

services:
  backend:
    build: .
    expose:
      - "8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://114.202.187.179:3306/safesignal_website
      SPRING_DATASOURCE_USERNAME: asincnt
      SPRING_DATASOURCE_PASSWORD: asincnt1013
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx384m -XX:+UseG1GC"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend