spring:
  application:
    name: demo

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates
    suffix: .html

  datasource:
    url: jdbc:mariadb://db:3306/safesignal_website  # ← IP 대신 db로 변경
    #url: jdbc:mariadb://114.202.187.179:3306/safesignal_website
    username: asincnt
    password: asincnt1013
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 8085

cors:
  cors:
    allowed-origins: "http://localhost:5173,https://safesignal.cloud,https://www.safesignal.cloud"

logging:
  level:
    root: info
    org.springframework: info